### ISSUE TITLE
How to set window size in jest test?

### ISSUE THREAD

**Issue by grantspilsbury** [ReactTraining/react-media#93] opened 2018-07-26 04:10 UTC
How should I setup a test where a different component is rendered depending on screen size? 

This is the component:

    <Media query={`(max-width: ${theme.screenSizes.sm.max}px)`}>
      {matches => (matches ? this.renderMobileView() : this.renderDesktopView())}
    </Media>

It only executes `renderDesktopView` but I'd like to also test `this.renderMobileView()`. 
I've added this to my test `global.window.innerWidth = 300;` with no success

**Comment by ethanova** [comment] 2018-07-26 19:17
adding
`global.window.dispatchEvent(new Event('resize'));`
after the innerWidth set also doesn't work

**Comment by edorivai** [comment] 2018-08-27 09:31
The tests here [manually mock](https://github.com/ReactTraining/react-media/blob/master/modules/__tests__/Media-test.js#L29) the `window.matchMedia` API. Would something like that work for you?

```js
window.matchMedia = {
  matches: true, // <-- Set according to what you want to test
  addListener: () => {},
  removeListener: () => {}
}

...run your test
```

**Comment by edorivai** [comment] 2018-08-30 07:48
@ethanova Your snipped actually looks good to me, so I'm guessing it's a setup issue.

Did you try `import * as Media from 'react-media'`?

**Comment by edorivai** [comment] 2018-08-30 13:43
I guess it depends on your setup. If you're using "plain es6" you shouldn't need the `* as`. Maybe if you share a minimal reproduction repo I can help you out further, but just from your test file I cannot see why you'd need the `* as`.

**Comment by ethanova** [comment] 2018-08-30 13:54
Ah dang, whatever the setup is for this project makes it so that the test requires `* as Media` but when changed in actual components it breaks the React App, so I can't keep the import at `* as Media`. Which means that I can't keep the test 😢

**Comment by edorivai** [comment] 2018-08-30 13:56
Is it a typescript project?

In that case take a look at the `allowSyntheticDefaultImports` flag which you should be able to set in your `tsconfig.json`

**Comment by ethanova** [comment] 2018-08-30 14:53
Looks like that might have broken some other things `TypeError: Adapter is not a constructor`
```3 | import * as Adapter from 'enzyme-adapter-react-16';
      4 | 
    > 5 | Enzyme.configure({ adapter: new Adapter() });```

**Comment by edorivai** [comment] 2018-08-30 15:07
Yeah, if you set that flag, you won't need any `* as` anymore :smile: :

```js
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });
```

**Comment by edorivai** [comment] 2018-08-31 07:30
@ethanova It seems to me that your issues are not `react-media` specific anymore, so I'm going to close this issue.

@grantspilsbury Please let me know if [the proposed solution](#issuecomment-416170644) doesn't work for you!

**Closed by edorivai** 2018-08-31 07:30 UTC

**Comment by Khrystyna** [comment] 2019-04-19 14:07
@edorivai I am experiencing another issue, close to this one, maybe you can help me out. 

I have component which has two `<Media>` components, one for mobile media query and another for desktop.  

When I test it with jest, using your snippet above (`matches: true,`) it renders both components, obviously. How can I test, for example, mobile view, so only one component, the one for mobile query, is rendered? I tried solution with setting `window.innerWidth`  and then triggering `resize` event, but it doesn't help.

**Comment by Khrystyna** [comment] 2019-04-26 07:44
I found a solution, maybe not the prettiest one, but it works. Method `matchMedia` takes media-query string as parameter, so I am just matching it to the one I want to test:

`  global.matchMedia = media => ({
      addListener: () => {},
      removeListener: () => {},
      matches: media === '(min-width: 545px)',
    });
`

**Comment by Neelimaordre** [comment] 2019-05-24 10:16
Hi Khrystyna, 
WHat is media in matches: media === '(min-width: 545px)',.
Thank you :)

**Comment by edorivai** [comment] 2019-05-24 10:55
@Neelimaordre It's on the first line of the snippet; the argument passed into the `matchMedia` function.

@Khrystyna basically hacks overwrites the original `window.matchMedia` with a hardcoded one, to define that the media query only matches when the query is equal to `'min-width: 545px'`.

**Comment by AmaanKulshreshtha** [comment] 2019-10-13 14:53
[This solution](https://stackoverflow.com/questions/46221210/jest-enzyme-how-to-test-at-different-viewports) could give you some inspiration

**Comment by 28JayG** [comment] 2022-07-08 08:58
> 

@Khrystyna can you send a screenshot of how you solved it using the matchMedia function?

**Comment by gentax** [comment] 2024-06-13 08:50
> I found a solution, maybe not the prettiest one, but it works. Method `matchMedia` takes media-query string as a parameter, so I am just matching it to the one I want to test:
> 
> ```
> global.matchMedia = media => ({
>       addListener: () => {},
>       removeListener: () => {},
>       matches: media === '(min-width: 545px)',
> });
> ```

thanks! worked perfectly! new stuff learned ;)
