### ISSUE TITLE
How to forward refs/make <Media> more transparent?

### ISSUE THREAD

**Issue by devinrhode2** [ReactTraining/react-media#131] opened 2019-04-30 20:12 UTC
Some code I am wrapping in a `<Media>` element has various `ref`'s - when I wrap the divs with the `ref`'s in a `<Media>` element, the refs are no longer defined for my component.

So basically I have:
```
<ComponentA>
  <div ref="foo">
    {this.props.stuff.map((things, i) => {
      <Media query="whatever">
        <div ref={'displayText' + i}>{some_text}</div>
      </Media>
    }}
  </div>
</ComponentA>
```
ComponentA expects `this.refs.displayText0`... to be defined. But once I wrap my `<div ref={'displayText' + i}` divs in a Media element, the refs are no longer defined on my parent ComponentA. I am curious if I could forward refs, or somehow make the react Media element more invisible/transparent.

**Comment by devinrhode2** [comment] 2019-04-30 20:17
I was reading some react documentation on forwarding ref's with HOC's here: https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components
I think react-media would need to define some sort of api for that though... I forked react-media and looked at how this could be done, but since I'm new to react, am not sure if this is the correct approach.

**Comment by edorivai** [comment] 2019-04-30 20:22
Hi @devinrhode2, not to be dismissive, but are you sure you need a ref? This page of the docs provides some good background on when one would want to use a ref: https://reactjs.org/docs/refs-and-the-dom.html

**Comment by devinrhode2** [comment] 2019-04-30 20:30
I wish I didn't need a ref but the code is necessary using the refs is
necessary. It's a bit complicated and foreign to me, but it's not like it's
some spaghetti code from hell ;)

**Comment by edorivai** [comment] 2019-04-30 20:33
It also seems to me that you're using the old version of refs. From the docs, refs are used like this:

```jsx
class AutoFocusTextInput extends React.Component {
  constructor(props) {
    super(props);
    this.textInput = React.createRef();
  }

  componentDidMount() {
    this.textInput.current.focusTextInput();
  }

  render() {
    return (
      <CustomTextInput ref={this.textInput} />
    );
  }
}
```

I'm sorry, I'm actually not too familiar with refs myself, since you so hardly need them.

**Comment by devinrhode2** [comment] 2019-04-30 20:37
I may be able to use callback refs to achieve something similar for react 15

**Comment by edorivai** [comment] 2019-04-30 20:44
Heh, yeah, you're using the _really, really_ old version of refs. I didn't quite realize how old, but even the oldest legacy docs that are still online flag the "string refs" as being legacy, and they highly recommend moving over to callback refs: https://react-legacy.netlify.com/docs/refs-and-the-dom.html#legacy-api-string-refs

I'll close this for now, feel free to open a new issue if you're still experiencing issues with callback refs!

**Closed by edorivai** 2019-04-30 20:44 UTC

**Comment by devinrhode2** [comment] 2019-04-30 20:48
thanks Edo!

**Comment by edorivai** [comment] 2019-04-30 20:59
Ooh, found some more context, in [this comment](https://github.com/facebook/react/pull/8333#issuecomment-271648615) Dan mentions why text refs break with the "render callback" pattern, which is what we're using here. This seems the be the root cause of your issues.

> It doesn't work as most people would expect with the "render callback" pattern (e.g. `<DataGrid renderRow={this.renderRow} />`) because the ref would get placed on DataGrid for the above reason.
